# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-02 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20170901_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Main Heading')),
                ('details', models.TextField(blank=True, max_length=500, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(blank=True, max_length=500, verbose_name='Details')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/avatars/', verbose_name='Image')),
                ('price_original', models.CharField(blank=True, max_length=150, verbose_name='Original Price')),
                ('price_offer', models.CharField(blank=True, max_length=150, verbose_name='Offer Price')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, max_length=500, on_delete=django.db.models.deletion.CASCADE, to='contents.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='heading',
            field=models.CharField(max_length=200, verbose_name='Main Heading'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='subheading',
            field=models.CharField(blank=True, max_length=250, verbose_name='Heading 2'),
        ),
    ]
